### ISSUE TITLE
Strict validation set to false by default

### ISSUE THREAD

**Issue by connorjacobsen** [thoughtbot/json_matchers#26]
The `json-schema` gem's validator sets `strict: false` by [default](https://github.com/ruby-json-schema/json-schema/blob/master/lib/json-schema/validator.rb#L28). Should the default for `json_matchers` be the same? Turning on strict causes the validator to completely ignore the required fields.

I would imagine the current default for strict is nice for simple CRUD APIs, but I would also imagine that it doesn't make as much sense for more complicated applications. It also seems to go against a major part of the JSON schema spec. I would also assert that having to explicitly state which properties are required would be a good development practice.

Thoughts?

**Comment by seanpdoyle** [comment]
Thanks for opening this issue!

This seems related to https://github.com/thoughtbot/json_matchers/issues/9.

A possible workaround (available at the moment) is to pass `strict: false` to the matcher.

This workaround was introduced by https://github.com/thoughtbot/json_matchers/pull/11.

https://github.com/thoughtbot/json_matchers/issues/9#issue-107978511 suggests setting `strict: false` when the schema includes a `required` key. That might be a suitable solution.

**Comment by connorjacobsen** [comment]
Currently I am passing `strict: false` to the matcher, which works nicely. This is not meant to be a bug report, just a discussion of what the expected behavior should be.

I would support setting `strict: false` when the schema includes a `required` key.

**Comment by seanpdoyle** [comment]
@connorjacobsen please comment on https://github.com/thoughtbot/json_matchers/pull/28.

Closing this issue.
