### ISSUE TITLE
type for an attribute that can be null or an object

### ISSUE THREAD

**Issue by dza2000** [thoughtbot/json_matchers#38]
```
"properties" : {
    "title" : { "type" : "string" },
    "app_name" : { "type" : "string" },
    "app_bundle_id" : { "type" : "string" },
    "root_menu" : { "type" : ["object", "null"],
                    "$ref" : "menu.json" }
  }
```
So I was thinking that should work, but in my test with a `nil` root_menu attribute, it's failing based on NilClass not matching the `$ref` at menu.json.  Any ideas?

**Comment by seanpdoyle** [comment]
If you're still experiencing this, you might have better luck opening this issue against the validator gem's repository ([`ruby-json-schema/json-schema`](https://github.com/ruby-json-schema/json-schema/issues)), since`json_matchers` delegates all validation responsibility to that gem.
