### ISSUE TITLE
Configure gem to default to strict

### ISSUE THREAD

**Issue by pclalv** [thoughtbot/json_matchers#40]
something like
```ruby
# spec/support/json_matchers.rb

JsonMatchers.strict_matching? = true
```

**Comment by seanpdoyle** [comment]
@pclalv you can now configure `JsonMatchers` with default options to be passed to all matchers:

https://github.com/thoughtbot/json_matchers/tree/c9abdf9811d18a9d1bd460ef03977b6d5432df52#default-matcher-options

**Comment by pclalv** [comment]
sick, thanks so much! :)
