### ISSUE TITLE
Feature Request - match_json_schema matcher

### ISSUE THREAD

**Issue by wayne5540** [thoughtbot/json_matchers#42]
Hi, thanks for all hard works to make this gem, it's really helpful. I have a feature request and want to discuss, created a PR to describe the feature to see if this make sense :) 

## Requested feature and reason
Sometimes I only want to test nested object like `JSON(response.body)['nested_object']`, I think it's more flexible to not using `response.body` but just JSON-string at `JsonMatchers::Matcher#matches?`.

Anyone thinks it's a good idea to support this? Or having a better idea how to approach this? Willing to have discussion, thanks 😸 

## Usage
```ruby
# spec/requests/posts_spec.rb

describe "GET /posts" do
  it "returns Posts" do
    get posts_path, format: :json

    expect(response.status).to eq 200
    expect(response.body).to match_json_schema("posts")
  end
end
```

**Comment by seanpdoyle** [comment]
Released as part of https://github.com/thoughtbot/json_matchers/releases/tag/v0.6.0.

Thanks!

**Comment by wayne5540** [comment]
Thanks, nice approach 👍
