### ISSUE TITLE
Store schemas as yaml files

### ISSUE THREAD

**Issue by r00takaspin** [thoughtbot/json_matchers#55]
I think it will be very useful to store schemas in pretty yaml format. Any plans to implement this feature in the future?

**Comment by seanpdoyle** [comment]
@r00takaspin currently, we don't plan on supporting other file formats for storing JSON Schema.

Could you elaborate on why declaring your schema as JSON files doesn't suit your needs?

If you haven't already, you should try https://github.com/square/fdoc. It has similar goals to this project, and its files are declared as YAML.
