### ISSUE TITLE
Not passing error messages correctly into Rspec

### ISSUE THREAD

**Issue by brobotics** [thoughtbot/json_matchers#56]
I am running `match_response_schema` from Rspec. Instead of receiving meaningful errors, I receive a type error.
 
From investigation, error messages appear to not be carried through correctly from JsonMatchers::Matcher#matches?L17

I am receiving `no implicit conversion of Hash into String` from Rspec. However, when I look at the errors themselves in JsonMatchers::Matcher, I can see:

```
[{:schema=>,
  :fragment=>,
  :message=>"The property '#/bar' did not contain a required property of 'errors' in schema file:///foo.json#",
  :failed_attribute=>"PropertiesV4"},
 {:schema=>,
  :fragment=>,
  :message=>"The property '#/foo' contained undefined properties: 'email' in schema file:///foo.json#",
  :failed_attribute=>"PropertiesV4"},
 {:schema=>,
  :fragment=>\,
  :message=>"The property '#/baz' contained undefined properties: 'details, activity, chart' in schema file:///foo.json",
  :failed_attribute=>"PropertiesV4"}]
```

**Comment by seanpdoyle** [comment]
@brobotics I've created https://github.com/thoughtbot/json_matchers/pull/57 to try and reproduce what you're seeing, but I wasn't able to.

Would you mind forking that PR to reproduce your error?

If not, could you share some more information? 

What version of the gem are you using?

Could you share one of the troublesome schemas?

Could you share one of the troublesome JSON documents?

**Comment by jsmestad** [comment]
I get this when using `oj` as my JSON parser, not sure if that helps @seanpdoyle

**Comment by jsmestad** [comment]
@seanpdoyle any chance of getting the #58 PR merged?

**Comment by seanpdoyle** [comment]
I think this is addressed by https://github.com/thoughtbot/json_matchers/pull/59 and https://github.com/thoughtbot/json_matchers/pull/61.

If that's not the case, I'll gladly re-open.
