### ISSUE TITLE
Schema Root + Path

### ISSUE THREAD

**Issue by chrishough** [thoughtbot/json_matchers#83]
Is it possible to setup a root for your schemas i.e. `spec/schemas` and then pass in a full path i.e. `match_response_schema('api/v1/meta')`

Unless I am missing something this is not supported.

**Comment by seanpdoyle** [comment]
@chrishough this has been supported for some time now.

I've opened https://github.com/thoughtbot/json_matchers/pull/84 to clarify that and to add explicit test coverage ensuring it's supported.

Could you share an example of a failing test, along with whatever configuration has been overridden?

**Comment by chrishough** [comment]
No worries, happy to help. 

Here is how I setup the directory `JsonMatchers.schema_root = 'spec/schemas'` and inside of that folder I would like to setup sub directories i.e. `api/v1/mode/` for example. 

If I tried to use `match_response_schema('api/v1/model')` never worked.

**Comment by chrishough** [comment]
The model is just an example, in this case it would be `model.json`

**Comment by chrishough** [comment]
I cracked that open, and the path looks correct, however, I am getting...
```
JSON::Schema::ReadFailed:
       Read of file at /spec/schemas/api/v1/test.json failed
```

**Comment by chrishough** [comment]
This is very odd @seanpdoyle because I just tried this and the same error is happening...
```
  def self.path_to_schema(schema_name)
    # binding.pry
    # Pathname(schema_root).join("#{schema_name}.json")
    Rails.root.join('spec', 'schemas', "#{schema_name}.json")
  end```

**Comment by chrishough** [comment]
@seanpdoyle I found one issue here, this `JsonMatchers.schema_root = 'spec/schemas'` **can not** have a forward slash in it `JsonMatchers.schema_root = '/spec/schemas'`, however, I have clearly broken json and the properties are letting it pass so I have to adjust that.

**Comment by chrishough** [comment]
That was the only issue, a solid `/` and I now have 50 more grey hairs.  Thank you again.

**Comment by seanpdoyle** [comment]
@chrishough thanks for working through this! 

The upside is that this is now _explicitly_ covered by the test suite!
