### ISSUE TITLE
refs from referenced files are not resolved

### ISSUE THREAD

**Issue by richardlarocque** [thoughtbot/json_matchers#92]
In complex schemas were the root contains a "$ref" to a file which contains a "$ref" to yet another file, it looks like the second level of references are not resolved.

In case that seems too hand-wavy, I'll attach a PR that includes test cases that demonstrate the behavior I believe to be incorrect.

I suspect that this bug might explain a few other open tickets, but I'm reluctant to propose resolve-as-dupe-ing without more investigation.

**Comment by KevinSjoberg** [comment]
Would really like to get this one merged. Anything I can do to help moving the needle?

**Comment by seanpdoyle** [comment]
I think this was resolved by https://github.com/thoughtbot/json_matchers/pull/93.

I'm going to close this for now. If it's still an issue, could you say so and I'll reopen it.

Thanks!
